---
title: "Abate bovino"
description: ""
author: "Ítalo Marques-Monteiro"      
date: "2023-09-11"
output: html_document
---

```{r}
library(tidyverse)
```

Conjunto de dados
```{r}
ufs  <- sidrar::get_sidra(
    api = "/t/1092/n3/all/v/284/p/last%201/c12716/115236/c18/55,56,111734,111735/c12529/118225") |>
    janitor::clean_names("snake") |>
    dplyr::select(
        valor, tipo_de_rebanho_bovino, unidade_da_federacao,
            categoria = tipo_de_rebanho_bovino,
            uf = unidade_da_federacao
    ) |>
    dplyr::mutate(uf = as.factor(uf)) |>
    dplyr::glimpse()
```


Fonte, cores e assinatura
```{r}
font <- "Josefin Sans"
font2 <- "Open Sans"

# Use the font_add_google() function to load fonts from the web
sysfonts::font_add_google(family=font, font, db_cache = FALSE)
sysfonts::font_add_google(family=font2, font2, db_cache = FALSE)

sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf") # nolint

theme_set(theme_minimal(base_family = font2, base_size = 3))

showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)

github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"

bg <- "white"
txt_col <- "grey90"
colors <- "grey40"
fundo <- "#283d44"
```

Participação das UFs no abate bovino do Brasil
```{r}
per_abt_total <- ufs |>
    dplyr::group_by(uf) |>
    dplyr::summarize(
        total = sum(valor, na.rm = TRUE),
        percent = total / 9075548) |>
    dplyr::mutate(perc2 = scales::percent(total / 9075548, accuracy = .1, trim = FALSE)) |>
    dplyr::arrange(desc(perc2)) #|> print(n = 27)

title_text <- glue::glue('Participação das UF no abate total de bovinos') # nolint
subtitle_text <- glue::glue("")
caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>", # nolint
  #"**Nota:** As Unidades da Federação, Amapá, Distrito Federal e Paraíba não apresentaram dados<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey90'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #1a96fc;'>{linkedin_icon};</span> 
  <span style='color: grey90'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey90'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #fd5257;'>{instagram_icon};</span>
  <span style='color: grey90'>{instagram_username}</span>"
)

perc_abt_ufs <- per_abt_total |>
    dplyr::mutate(
        color = case_when(
          row_number() == 1 ~ "#1a96fc",
          row_number() == 2 ~ "#fd9850",
          row_number() == 3 ~ "#f8b83c",
          ## all others should be gray      
          TRUE ~ "gray70"),
        color = forcats::as_factor(color)
    ) |>
    ggplot(aes(x = percent, y = reorder(uf, percent))) +
        geom_col(aes(fill = color), color = "grey50", size = 1, width = 0.8)+
        scale_fill_identity(guide = "none") +
        geom_text(mapping = aes(label = scales::percent(percent, accuracy = 0.1)),
             position = position_dodge(0.9),
             family = font,
             fontface = "bold",
             size = 4,
             color = "gray90",
             vjust = 0.5,
              hjust = -0.3) +
        theme_void() +
        labs(
            title = title_text,
            subtitle = "4º trimestre de 2023",
            caption = caption_text) +
        theme(
            plot.title = ggtext::element_markdown(face = "bold", family = font, color = "gray90", size = 25, hjust = 0.1),
            plot.subtitle = element_text(family = font2, size = 15, color = "gray70", hjust = 0.1),
            plot.caption = ggtext::element_markdown(family = font2, hjust = 0, margin = margin(10,0,0,0), size = 8, color = txt_col, lineheight = 1.2), # nolint
            axis.text.y = element_text(family = font2, face = "bold", color = "gray60", size = 12, hjust = 1),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_rect(fill = fundo, color = fundo),
            plot.background = element_rect(fill = fundo)
        ) 

abt_ufs <- data.frame(image = ".vscode/Images/mapa_abt_ufs.png") 

perc_abt_ufs <- perc_abt_ufs +
    ggimage::geom_image(aes(x = 0.10, y = 10, image = image), data = abt_ufs,  size = 1.1)  # nolint

ggsave(".vscode/Images/perc_abt_ufs.png", plot = perc_abt_ufs, width = 14, height = 9, dpi = 300)
```


Participação de Vacas no abate nacional
```{r}
ufs_vacas <- ufs |>
    dplyr::filter(categoria == "Vacas") |>
    dplyr::mutate(uf = as.factor(uf)) |>
    dplyr::glimpse()
ufs_vacas |>
    dplyr::summarize(
        total = sum(valor, na.rm = TRUE)
        )

prop_vaca <- ufs_vacas |>
    dplyr::group_by(uf) |>
    dplyr::summarize(
        total = sum(valor, na.rm = TRUE),
        perc = total / 2516575) |>
    dplyr::mutate(perc2 = scales::percent(total / 2516575, accuracy = .1, trim = FALSE)) |>
    dplyr::arrange(desc(perc2))

title_text <- glue::glue('Participação de vacas no abate nacional') # nolint
subtitle_text <- glue::glue("")
caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>", # nolint
  "**Nota:** As unidades da federação, Amapá, Distritio Federal e Paraíba não apresentaram dados<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey90'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #1a96fc;'>{linkedin_icon};</span> 
  <span style='color: grey90'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey90'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #fd5257;'>{instagram_icon};</span>
  <span style='color: grey90'>{instagram_username}</span>"
)

perc_abate_vaca <- prop_vaca |>
    dplyr::mutate(
        color = case_when(
          row_number() == 1 ~ "#1a96fc",
          row_number() == 2 ~ "#fd9850",
          row_number() == 3 ~ "#f8b83c",
          ## all others should be gray
          TRUE ~ "gray70"),
        color = forcats::as_factor(color)
    ) |>
    ggplot(aes(x = perc, y = reorder(uf, perc))) +
        geom_col(aes(fill = color), color = "grey50", size = 1, width = 0.8)+
        scale_fill_identity(guide = "none") +
        geom_text(mapping = aes(label = scales::percent(perc, accuracy = 0.1)),
             position = position_dodge(0.9),
             family = font,
             fontface = "bold",
             size = 4,
             color = "gray90",
             vjust = 0.5,
              hjust = -0.3) +
        theme_void() +
        labs(
            title = title_text,
            subtitle = "4º trimestre de 2023",
            caption = caption_text) +
        theme(
            plot.title = ggtext::element_markdown(face = "bold", family = font, color = "gray90", size = 25, hjust = 0.1),
            plot.subtitle = element_text(family = font2, size = 15, color = "gray70", hjust = 0.1),
            plot.caption = ggtext::element_markdown(family = font2, hjust = 0, margin = margin(10,0,0,0), size = 8, color = txt_col, lineheight = 1.2), # nolint
            axis.text.y = element_text(family = font2, face = "bold", color = "gray60", size = 12, hjust = 1),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_rect(fill = fundo, color = fundo),
            plot.background = element_rect(fill = fundo)
        ) 

abt_vaca <- data.frame(image = ".vscode/Images/mapa_abt_vaca.png") 
perc_abate_vaca <- perc_abate_vaca +
    ggimage::geom_image(aes(x = 0.08, y = 10, image = image), data = abt_vaca,  size = 1.1)  # nolint

ggsave(".vscode/Images/perc_abate_vaca.png", plot = perc_abate_vaca, width = 14, height = 9, dpi = 300)
```


Participação de bois no abate nacional
```{r}
ufs_boi <- ufs |>
    dplyr::filter(categoria == "Bois") |>
    dplyr::mutate(uf = as.factor(uf)) |>
    dplyr::glimpse()

ufs_boi |>
    dplyr::summarize(
        total_boi = sum(valor, na.rm = TRUE)
        )

prop_boi <- ufs_boi |>
    dplyr::group_by(uf) |>
    dplyr::summarize(
        total_boi = sum(valor, na.rm = TRUE),
        perc_boi = total_boi / 5115884) |>
    dplyr::mutate(percentual_boi = scales::percent(total_boi / 5115884, accuracy = .1, trim = FALSE))

prop_boi_cor <- prop_boi |>
    dplyr::arrange(desc(perc_boi)) |>
  mutate(
    color = case_when(
      row_number() == 1 ~ "#1a96fc",
      row_number() == 2 ~ "#fd9850",
      row_number() == 3 ~ "#f8b83c",
      ## all others should be gray
      TRUE ~ "gray70" )
  )

title_text <- glue::glue('Participação de bois no abate nacional') # nolint
subtitle_text <- glue::glue("")
caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>", # nolint
  "**Nota:** As unidades da federação, Amapá, Distritio Federal e Paraíba não apresentaram dados<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey90'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #1a96fc;'>{linkedin_icon};</span> 
  <span style='color: grey90'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey90'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #fd5257;'>{instagram_icon};</span>
  <span style='color: grey90'>{instagram_username}</span>"
)

perc_abt_boi <- prop_boi_cor |>
    ggplot(aes(x = perc_boi, y = reorder(uf, perc_boi))) +
        geom_col(aes(fill = color), color = "grey50", size = 1, width = 0.8)+
        scale_fill_identity(guide = "none") +
        geom_text(mapping = aes(label = scales::percent(perc_boi, accuracy = 0.1)),
             position = position_dodge(0.9),
             family = font,
             fontface = "bold",
             size = 4,
             color = "gray90",
             vjust = 0.5,
              hjust = -0.3
              ) +
        theme_void() +
        labs(
            title = title_text,
            subtitle = "4º trimestre de 2023",
            caption = caption_text
            ) +
        theme(
            plot.title = ggtext::element_markdown(face = "bold", family = font, color = "gray90", size = 25, hjust = 0.1),
            plot.subtitle = element_text(family = font2, size = 15, color = "gray70", hjust = 0.1),
            plot.caption = ggtext::element_markdown(family = font2, hjust = 0, margin = margin(10,0,0,0), size = 8, color = txt_col, lineheight = 1.2), # nolint
            axis.text.y = element_text(family = font2, face = "bold", color = "gray60", size = 12, hjust = 1),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_rect(fill = fundo, color = fundo),
            plot.background = element_rect(fill = fundo)
        ) 

abt_boi <- data.frame(image = ".vscode/Images/mapa_abt_boi.png") 
perc_abt_boi <- perc_abt_boi +
    ggimage::geom_image(aes(x = 0.10, y = 10, image = image), data = abt_boi,  size = 0.9)  # nolint

ggsave(".vscode/Images/perc_abt_boi.png", plot = perc_abt_boi, width = 14, height = 9, dpi = 300)
```


Participação de novilhas no abate nacional
```{r}
ufs_novilha <- ufs |>
    dplyr::filter(categoria == "Novilhas") |>
    dplyr::mutate(uf = as.factor(uf)) |>
    dplyr::glimpse()

ufs_novilha |>
    dplyr::summarize(
        total_novilha = sum(valor, na.rm = TRUE)
        )

prop_novilha <- ufs_novilha |>
    dplyr::group_by(uf) |>
    dplyr::summarize(
        total_novilha = sum(valor, na.rm = TRUE),
        perc_novilha = total_novilha / 1027576
        ) |>
    dplyr::mutate(percentual_novilha = scales::percent(total_novilha / 1027576, accuracy = .1, trim = FALSE))

prop_novilha_cor <- prop_novilha |>
    dplyr::arrange(desc(perc_novilha)) |>
  mutate(
    color = case_when(
      row_number() == 1 ~ "#1a96fc",
      row_number() == 2 ~ "#fd9850",
      row_number() == 3 ~ "#f8b83c",
      ## all others should be gray
      TRUE ~ "gray70"
    )
  )

title_text <- glue::glue('Participação de novilhas no abate nacional') # nolint
subtitle_text <- glue::glue("")
caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>", # nolint
  "**Nota:** As unidades da federação, Amapá, Distritio Federal e Paraíba não apresentaram dados<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey90'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #1a96fc;'>{linkedin_icon};</span> 
  <span style='color: grey90'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey90'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #fd5257;'>{instagram_icon};</span>
  <span style='color: grey90'>{instagram_username}</span>"
)

perc_abt_novilha <- prop_novilha_cor |>
    ggplot(aes(x = perc_novilha, y = reorder(uf, perc_novilha))) +
        geom_col(aes(fill = color), color = "grey50", size = 1, width = 0.8)+
        scale_fill_identity(guide = "none") +
        geom_text(mapping = aes(label = scales::percent(perc_novilha, accuracy = 0.1)),
             position = position_dodge(0.9),
             family = font,
             fontface = "bold",
             size = 4,
             color = "gray90",
             vjust = 0.5,
              hjust = -0.3
              ) +
        theme_void() +
        labs(
            title = title_text,
            subtitle = "4º trimestre de 2023",
            caption = caption_text) +
        theme(
            plot.title = ggtext::element_markdown(face = "bold", family = font, color = "gray90", size = 25, hjust = 0.1),
            plot.subtitle = element_text(family = font2, size = 15, color = "gray70", hjust = 0.1),
            plot.caption = ggtext::element_markdown(family = font2, hjust = 0, margin = margin(10,0,0,0), size = 8, color = txt_col, lineheight = 1.2), # nolint
            axis.text.y = element_text(family = font2, face = "bold", color = "gray60", size = 12, hjust = 1),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_rect(fill = fundo, color = fundo),
            plot.background = element_rect(fill = fundo)
        ) 

abt_novilha <- data.frame(image = ".vscode/Images/mapa_abt_novilha.png") 
perc_abt_novilha <- perc_abt_novilha +
    ggimage::geom_image(aes(x = 0.17, y = 11, image = image), data = abt_novilha,  size = 0.9)  # nolint

ggsave(".vscode/Images/perc_abt_novilha.png", plot = perc_abt_novilha, width = 14, height = 9, dpi = 300)
```


Participação de novilhos no abate nacional
```{r}
ufs_novilho <- ufs |>
    dplyr::filter(categoria == "Novilhos") |>
    dplyr::mutate(uf = as.factor(uf)) |>
    dplyr::glimpse()

ufs_novilho |>
    dplyr::summarize(
        total_novilho = sum(valor, na.rm = TRUE)
        )

prop_novilho <- ufs_novilho |>
    dplyr::group_by(uf) |>
    dplyr::summarize(
        total_novilho = sum(valor, na.rm = TRUE),
        perc_novilho = total_novilho / 372911
        ) |>
    dplyr::mutate(percentual_novilho = scales::percent(total_novilho / 372911, accuracy = .1, trim = FALSE))

prop_novilho_cor <- prop_novilho |>
    dplyr::arrange(desc(perc_novilho)) |>
  mutate(
    color = case_when(
      row_number() == 1 ~ "#1a96fc",
      row_number() == 2 ~ "#fd9850",
      row_number() == 3 ~ "#f8b83c",
      ## all others should be gray
      TRUE ~ "gray70"
    )
  )

title_text <- glue::glue('Participação de novilhos no abate nacional') # nolint
subtitle_text <- glue::glue("")
caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>", # nolint
  "**Nota:** As unidades da federação, Amapá, Distritio Federal e Paraíba não apresentaram dados<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey90'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #1a96fc;'>{linkedin_icon};</span> 
  <span style='color: grey90'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey90'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: #fd5257;'>{instagram_icon};</span>
  <span style='color: grey90'>{instagram_username}</span>"
)

perc_abt_novilho <- prop_novilho_cor |>
    ggplot(aes(x = perc_novilho, y = reorder(uf, perc_novilho))) +
        geom_col(aes(fill = color), color = "grey50", size = 1, width = 0.8)+
        scale_fill_identity(guide = "none") +
        geom_text(mapping = aes(label = scales::percent(perc_novilho, accuracy = 0.1)),
             position = position_dodge(0.9),
             family = font,
             fontface = "bold",
             size = 4,
             color = "gray90",
             vjust = 0.5,
              hjust = -0.3
              ) +
        theme_void() +
        labs(
            title = title_text,
            subtitle = "4º trimestre de 2023",
            caption = caption_text
            ) +
        theme(
            plot.title = ggtext::element_markdown(face = "bold", family = font, color = "gray90", size = 25, hjust = 0.1),
            plot.subtitle = element_text(family = font2, size = 15, color = "gray70", hjust = 0.1),
            plot.caption = ggtext::element_markdown(family = font2, hjust = 0, margin = margin(10,0,0,0), size = 8, color = txt_col, lineheight = 1.2), # nolint
            axis.text.y = element_text(family = font2, face = "bold", color = "gray60", size = 12, hjust = 1),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_rect(fill = fundo, color = fundo),
            plot.background = element_rect(fill = fundo)
        ) 

abt_novilho <- data.frame(image = ".vscode/Images/mapa_abt_novilho.png") 
perc_abt_novilho <- perc_abt_novilho +
    ggimage::geom_image(aes(x = 0.22, y = 11, image = image), data = abt_novilho,  size = 0.9)  # nolint

ggsave(".vscode/Images/perc_abt_novilho.png", plot = perc_abt_novilho, width = 14, height = 9, dpi = 300)

```


mapas 
```{r}
br <- geobr::read_state(code_state = "all", year = 2020) |>
    dplyr::glimpse()

rs <- br |> dplyr::filter(abbrev_state == "RS")
ms <- br |> dplyr::filter(abbrev_state == "MS") 
go <- br |> dplyr::filter(abbrev_state == "GO") 
sp <- br |> dplyr::filter(abbrev_state == "SP") 
mt <- br |> dplyr::filter(abbrev_state == "MT") 
pa <- br |> dplyr::filter(abbrev_state == "PA") 
ro <- br |> dplyr::filter(abbrev_state == "RO")
sc <- br |> dplyr::filter(abbrev_state == "SC")


"#1a96fc"
"#fd9850"
"#f8b83c"

mapa_abt_novilho <- br |>
    ggplot2::ggplot() +

        geom_sf(
            fill = "gray70",
            color = "gray30",
            size = 1,
            show.legend = FALSE) +
        geom_sf(data = rs,
        
            fill = "#1a96fc",
            color = "black",
            size = 2,
            show.legend = FALSE) +

        geom_sf(data = ms,
            fill = "#fd9850",
            color = "black",
            size = 1,
            show.legend = FALSE) +

        geom_sf(data = sc,
            fill = "#f8b83c",
            color = "black",
            size = 1,
            show.legend = FALSE) +

        theme_void() +
        theme(
            panel.background = element_blank(),
            plot.background = element_blank()
        )
mapa_abt_novilho
#ggsave(".vscode/Images/mapa_abt_novilho.png", plot = mapa_abt_novilho, dpi = 300)
```