---
title: "Cabeças Abatidas"
description: "Número de animais abatidos no 4º trimestre de 2023 (Bovinos)"
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Smart Data  
        
date: "2023-08-11"
output: html_document
---

```{r}
library(tidyverse)
```


Abate por categoria, BR
```{r}
abate_temp <- sidrar::get_sidra(
    api = "/t/1092/n1/all/v/284,285/p/all/c12716/115236/c18/55,56,111734,111735/c12529/118225") |>
    janitor::clean_names("snake") |>
    dplyr::glimpse()
```

```{r}
abt <- abate_temp |>
    dplyr::select(
        valor,
        categoria = tipo_de_rebanho_bovino,
        data_trimestre = trimestre_codigo,
        trimestre,
        variavel
    ) |>
    dplyr::mutate(
        data_trimestre = lubridate::yq(data_trimestre),
        ano = lubridate::year(data_trimestre)
    ) |>
    tidyr::pivot_wider(
        names_from = variavel,
        values_from = valor
    ) |>
    dplyr::rename(
        cabeca = `Animais abatidos`,
        carcaca = `Peso total das carcaças`
    ) |>
    dplyr::mutate(
        peso_car = carcaca / cabeca
    ) |>
    dplyr::glimpse()
```


```{r}
font <- "Josefin Sans"
font2 <- "Open Sans"

# Use the font_add_google() function to load fonts from the web
sysfonts::font_add_google(family=font, font, db_cache = FALSE)
sysfonts::font_add_google(family=font2, font2, db_cache = FALSE)

sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf") # nolint

theme_set(theme_minimal(base_family = font2, base_size = 3))

showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)
```

```{r}
github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"

caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>", # nolint
  "**Nota:** Dados agrupados por ano (1997 a 2023) e categoria (bois, vacas, novilhas e novilhos)<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: black;'>{github_icon};</span> 
  <span style='color: black'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: dodgerblue4;'>{linkedin_icon};</span> 
  <span style='color: black'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: black'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: black'>{instagram_username}</span>"
)
```

```{r}
bg <- "white"
txt_col <- "black"

pal=c(
      "#2f4b7c",
      "#665191",
      "#f95d6a",
      "#ffa600"
      )
# Ordem de empilhamento
order <- c("Bois", "Vacas", "Novilhas", "Novilhos")
```

```{r}
plot_abt <- abt |>
    dplyr::group_by(ano, categoria) |>
    dplyr::summarise(total = sum(cabeca)) |>
    dplyr::arrange(total) |>
    dplyr::mutate(categoria = factor(categoria, levels = order)) |> 
    ggplot(aes(ano, total, fill = categoria, label = categoria, color = categoria)) +
    ggstream::geom_stream(type = "ridge", bw = 1) + 
  
    scale_fill_manual(values=pal) +
    scale_color_manual(values=pal) +
    scale_x_continuous(breaks=c(2000, 2005, 2010, 2015, 2019, 2023),labels = c("2000", "2005", "2010", "2015", "2019", "2023")) +
    scale_y_continuous(expand = c(0,0)) +
    coord_cartesian(clip = "off") +

# Titulo
    annotate("text", x = 1997, y = 32000000,
             label = "Evolução do\nAbate Bovino",
             hjust=0,
             size=14,
             lineheight=.9,
             fontface="bold",
             family = font,
             color="black") +
    
# Bois
    annotate("text", x = 2023.2, y = 25000000,
           label = "Bois 18.27 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface = "bold", family = font2,
           color = pal[1]) +
# Vacas
    annotate("text", x = 2023.2, y = 10000000,
           label = "Vacas 9.99 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface ="bold",family = font2,
           color = pal[2]) +
# Novilhas
    annotate("text", x = 2023.2, y = 3500000,
           label = "Novilhas 4.18 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface = "bold",family = font2,
           color = pal[3]) +
# Novilhos
    annotate("text", x = 2023.2, y = 900000,
           label = "Novilhos 1.62 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface ="bold",family = font2,
           color = pal[4]) +

## Segmentos verticais
    geom_segment(aes(x = 2000, y = 0, xend = 2000, yend = 20000000+25000),color="black") +
    geom_point(aes(x = 2000, y = 20000000+25000),color="black") +
    annotate("text", x = 2000, y = 20500000+30000,
           label = "17 milhões cab.",
           hjust=0.5,
           size=3,
           lineheight=.8,
           fontface="bold",family=font2,
           color = txt_col) +

    geom_segment(aes(x = 2005, y = 0, xend = 2005, yend = 27000000+25000),color="black") +
    geom_point(aes(x = 2005, y = 27000000+25000),color="black") +
    annotate("text", x = 2005, y = 27500000+30000,
           label = "27.9 milhões cab.",
           hjust=0.5,
           size=3,
           lineheight=.8,
           fontface="bold",family=font2,
           color=txt_col) +
  
    geom_segment(aes(x = 2010, y = 0, xend = 2010, yend = 30000000+25000),color="black") +
    geom_point(aes(x = 2010, y = 30000000+25000),color="black") +
    annotate("text", x = 2010, y = 30500000+30000,
           label = "29.2 milhões cab.",
           hjust=0.5,
           size=3,
           lineheight=.8,
           fontface="bold",family=font2,
           color=txt_col) +
  
    geom_segment(aes(x = 2015, y = 0, xend = 2015, yend = 32000000+25000),color="black") +
    geom_point(aes(x = 2015, y = 32000000+25000),color="black") +
    annotate("text", x = 2015, y = 32500000+50000,
           label = "30.6 milhões cab",
           hjust=0.5,
           size=3,
           lineheight=.8,
           fontface="bold",family=font2,
           color=txt_col) +
  
    geom_segment(aes(x = 2019, y = 0, xend = 2019, yend = 33000000+50000),color="black") +
    geom_point(aes(x = 2019, y = 33000000+50000),color="black") +
    annotate("text", x = 2019, y = 33500000+50000,
           label = "32.4 milhões cab.",
           hjust=0.5,
           size=3,
           lineheight=.8,
           fontface="bold",family=font2,
           color=txt_col) +

    geom_segment(aes(x = 2023, y = 0, xend = 2023, yend = 36000000+25000),color="black") +
    geom_point(aes(x = 2023, y = 36000000+25000),color="black") +
    annotate("text", x = 2023, y = 36000000+30000,
           label = "34.06 milhões cab.",
           hjust = 1.1,
           size = 3,
           lineheight =.8,
           fontface="bold",family=font2,
           color=txt_col) +

    labs(caption = caption_text) +
    theme(
        axis.line.x = element_line(linewidth = .75),
        #panel.grid = element_blank(),
        panel.background = element_rect(fill = "white", color = "white"),
        panel.grid = element_line(color = "white"),
        plot.background = element_rect(fill = "white"),
        axis.text.y=element_blank(),
        axis.text.x = element_text(color=txt_col, size=10,margin = margin(5,0,0,0)),
        plot.margin = margin(20,120,20,20),
        legend.position = "none",
        plot.caption = ggtext::element_markdown(hjust=0, margin=margin(10,0,0,0), size=8, color=txt_col, lineheight = 1.2),
    )
plot_abt
```

```{r}
ggsave(".vscode/Images/EvolAbateCategoria.png",
    plot = plot_abt,
    dpi = 300,
    width = 15,
    height = 10,
    )
```

```{r}
abt |>
    dplyr::group_by(ano) |>
    dplyr::summarise(total = sum(cabeca), ) |>
    #dplyr::filter(ano %in% c(1997, 2002, 2008, 2013, 2018, 2023)) |>
    dplyr::arrange(desc(total)) |>
    print(n = 27)
```

```{r}
plot_abt1 <- abt |>
    dplyr::group_by(ano, categoria) |>
    dplyr::summarise(total = sum(cabeca)) |>
    dplyr::arrange(total) |>
    dplyr::mutate(categoria = factor(categoria, levels = order)) |> 
    ggplot(aes(ano, total, fill = categoria, label = categoria, color = categoria)) +
    geom_area() +
  
    scale_fill_manual(values=pal) +
    scale_color_manual(values=pal) +
    scale_x_continuous(breaks=c(1997, 2002, 2008, 2013, 2018, 2023),labels = c("1997", "2002", "2008", "2013", "2018", "2023")) +
    scale_y_continuous(expand = c(0,0)) +
    coord_cartesian(clip = "off") +

# Titulo
    annotate("text", x = 1997, y = 32000000,
             label = "Evolução do\nAbate Bovino",
             hjust=0,
             size=14,
             lineheight=.9,
             fontface="bold",
             family = font,
             color="black") +
    
# Bois
    annotate("text", x = 2023.2, y = 23000000,
           label = "Bois 18.27 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface = "bold", family = font2,
           color = pal[1]) +
# Vacas
    annotate("text", x = 2023.2, y = 10000000,
           label = "Vacas 9.99 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface ="bold",family = font2,
           color = pal[2]) +
# Novilhas
    annotate("text", x = 2023.2, y = 3500000,
           label = "Novilhas 4.18 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface = "bold",family = font2,
           color = pal[3]) +
# Novilhos
    annotate("text", x = 2023.2, y = 900000,
           label = "Novilhos 1.62 milhões cab.",
           hjust = 0,
           size = 3,
           lineheight =.8,
           fontface ="bold",family = font2,
           color = pal[4]) +

## Segmentos verticais
    geom_segment(aes(x = 1997, y = 0, xend = 1997, yend = 15500000+25000),color="black") +
    geom_point(aes(x = 1997, y = 15500000+25000),color="black") +
    annotate("text", x = 1997, y = 16000000+30000,
           label = "14.86 milhões cab.",
           hjust = 0.5,
           size=3,
           lineheight = .8,
           fontface ="bold",family = font2,
           color = txt_col) +

    geom_segment(aes(x = 2002, y = 0, xend = 2002, yend = 21000000+25000),color="black") +
    geom_point(aes(x = 2002, y = 21000000+25000),color="black") +
    annotate("text", x = 2002, y = 21500000+30000,
           label = "19.89 milhões cab.",
           hjust = 1.1,
           size = 3,
           lineheight =.8,
           fontface = "bold",family = font2,
           color = txt_col) +
  
    geom_segment(aes(x = 2008, y = 0, xend = 2008, yend = 29500000+25000),color="black") +
    geom_point(aes(x = 2008, y = 29500000+25000),color="black") +
    annotate("text", x = 2008, y = 30000000+30000,
           label = "28.68 milhões cab.",
           hjust = 0.2,
           size = 3,
           lineheight =.8,
           fontface ="bold",family = font2,
           color = txt_col) +
  
    geom_segment(aes(x = 2013, y = 0, xend = 2013, yend = 34900000+25000),color="black") +
    geom_point(aes(x = 2013, y = 34900000+25000),color="black") +
    annotate("text", x = 2013, y = 35500000+50000,
           label = "34.41 milhões cab",
           hjust = 0.5,
           size = 3,
           lineheight =.8,
           fontface ="bold",family = font2,
           color = txt_col) +
  
    geom_segment(aes(x = 2018, y = 0, xend = 2018, yend = 32500000+50000),color="black") +
    geom_point(aes(x = 2018, y = 32500000+50000),color="black") +
    annotate("text", x = 2018, y = 33000000+50000,
           label = "32.04 milhões cab.",
           hjust = 0.5,
           size = 3,
           lineheight = .8,
           fontface ="bold",family = font2,
           color = txt_col) +

    geom_segment(aes(x = 2023, y = 0, xend = 2023, yend = 34700000+25000),color="black") +
    geom_point(aes(x = 2023, y = 34700000+25000),color = "black") +
    annotate("text", x = 2023, y = 35100000+30000,
           label = "34.06 milhões cab.",
           hjust = 1.1,
           size = 3,
           lineheight =.8,
           fontface ="bold",family = font2,
           color = txt_col) +

    labs(caption = caption_text) +
    theme(
        axis.line.x = element_line(linewidth = .75),
        #panel.grid = element_blank(),
        panel.background = element_rect(fill = "white", color = "white"),
        panel.grid = element_line(color = "white"),
        plot.background = element_rect(fill = "white"),
        axis.text.y=element_blank(),
        axis.text.x = element_text(color = txt_col, size = 10,margin = margin(5,0,0,0)),
        plot.margin = margin(20,120,20,20),
        legend.position = "none",
        plot.caption = ggtext::element_markdown(hjust=0, margin = margin(10,0,0,0), size=8, color=txt_col, lineheight = 1.2),
    )
plot_abt1
```

```{r}
ggsave(".vscode/Images/EvolAbateCategoria1.png",
    plot = plot_abt1,
    dpi = 300,
    width = 15,
    height = 10,
    )
```
