---
title: "Carcaças bovinas abatidas"
description: "Peso das carcaças abatidas no 2º trimestre de 2023 (Bovonos, Suínos e Frangos)"
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Smart Data  
        
date: "2023-08-11"
output: html_document
---

```{r}
library(conflicted)
library(tidyverse)
```

```{r}
abate_temp <- sidrar::get_sidra(
    api = "/t/6829/n1/all/v/all/p/last%2010/c12716/115236/c79/all") |>
    janitor::clean_names("snake") |>
    dplyr::glimpse()
#abate_temp|> view()
```

```{r}
prev_abate <- abate_temp |>
    dplyr::select(valor, variavel, trimestre, tipo_de_rebanho) |>
    tidyr::pivot_wider(names_from = variavel, values_from = valor) |>
    janitor::clean_names("snake") |>
    dplyr::glimpse()
#prev_abate|>tibble::view()
```

```{r}
abate <- prev_abate |>
    dplyr::mutate(
        periodo = dplyr::case_when(
            trimestre == "1º trimestre 2021" ~ ("2021-Q1"),
            trimestre == "2º trimestre 2021" ~ ("2021-Q2"),
            trimestre == "3º trimestre 2021" ~ ("2021-Q3"),
            trimestre == "4º trimestre 2021" ~ ("2021-Q4"),
            trimestre == "1º trimestre 2022" ~ ("2022-Q1"),
            trimestre == "2º trimestre 2022" ~ ("2022-Q2"),
            trimestre == "3º trimestre 2022" ~ ("2022-Q3"),
            trimestre == "4º trimestre 2022" ~ ("2022-Q4"),
            trimestre == "1º trimestre 2023" ~ ("2023-Q1"),
            trimestre == "2º trimestre 2023" ~ ("2023-Q2"),
            TRUE~ trimestre
        ),
        periodo = lubridate::yq(periodo),
        ano = lubridate::year(periodo), .before = trimestre
    ) |>
    dplyr::mutate(
        peso_medio_carcaca = peso_total_das_carcacas / animais_abatidos
    ) |>
    dplyr::glimpse()
abate |>tibble::view()
```


```{r}
scaleFUN <- function(x) format(round(as.numeric(x), 0), nsmall = 0)

# Create line chart theme
theme_swd_line <-   theme(
  plot.title = element_text(size = rel(1.75), color = "#E46726"), #steelblue
  plot.margin = margin(20, 20, 20, 20),
  text = element_text(family = "Roboto", color = "#979797"),
  axis.title.x = element_text(hjust = 0, vjust = -0.5),
  axis.title.y = element_blank(),
  axis.text.y = element_blank(),
  line = element_blank(),
  rect = element_blank()
)
```

"#E46726"LARANJA, "#6D9EC1"AZUL 
```{r}
carcaca_2tri_2023 <- abate |>
    dplyr::filter(tipo_de_rebanho == "Bovinos") |>
    #dplyr::summarise(media = mean(peso_total_das_carcacas)) |>
    ggplot2::ggplot(aes(x = trimestre, y = peso_total_das_carcacas)) +
                geom_col(aes(fill = ifelse(
                    trimestre %in% c(
                        "2º trimestre 2022",
                            "1º trimestre 2023",
                                "2º trimestre 2023"),
                                    "high", "default")
                                    )
                            ) +
  scale_fill_manual(values = c(high = "#E46726", default = "grey45")) +
                geom_hline(yintercept = 1927320737., lty = 3, color = "gray30") +
                theme_swd_line  +
                scale_y_continuous(labels = scales::comma) +
                labs(title = "Abate de bovinos no Brasil (Peso total de carcaça-kg)",
                    subtitle = "# Relatório trimestral de abate
                    by Ítalo Monteiro
                    Source: IBGE [open data(2023)]",
                    x = "Trimestre"
                    ) +
                geom_text(
                    data = abate[abate$ano == 2023 &
                        abate$trimestre == "2º trimestre 2023" &
                            abate$tipo_de_rebanho == "Bovinos",],
                            aes(label = scaleFUN(peso_total_das_carcacas)),
                            hjust = 0.5,
                            vjust = -0.5,
                            size = 5,
                            color = "#E46726",
                            fontface = "bold") +
                geom_text(
                    data = abate[abate$ano == 2023 &
                        abate$trimestre == "1º trimestre 2023" &
                            abate$tipo_de_rebanho == "Bovinos",],
                            aes(label = scaleFUN(peso_total_das_carcacas)),
                            hjust = 0.5,
                            vjust = -0.8,
                            size = 4,
                            color = "gray50",
                            fontface = "bold") +
                geom_text(
                    data = abate[abate$ano == 2022 &
                        abate$trimestre == "2º trimestre 2022" &
                            abate$tipo_de_rebanho == "Bovinos",],
                            aes(label = scaleFUN(peso_total_das_carcacas)),
                            hjust = 0.5,
                            vjust = -0.5,
                            size = 4,
                            color = "gray50",
                            fontface = "bold") +
                scale_x_discrete(
                    limits = c(
                    "1º trimestre 2021",
                    "2º trimestre 2021",
                    "3º trimestre 2021",
                    "4º trimestre 2021",
                    "1º trimestre 2022",
                    "2º trimestre 2022",
                    "3º trimestre 2022",
                    "4º trimestre 2022",
                    "1º trimestre 2023",
                    "2º trimestre 2023")
                ) +
  guides(fill = FALSE) +
  annotate(
    "text", label = "Média do período",
    x = 2, y = 1970320737., size = 4, colour = "gray45"
  )
carcaca_2tri_2023
```

```{r}
ggsave("Images/carcaca_2tri_2023.png",
    plot = carcaca_2tri_2023,
    dpi = 1200,
    width = ,
    height = )
```


```{r}
peso_medio_carcaca_2tri_2023 <- abate |>
    dplyr::filter(tipo_de_rebanho == "Bovinos") |>
    dplyr::mutate(
    cor = case_when(
      trimestre == "2º trimestre 2023" ~ "goldenrod1",
      trimestre == "1º trimestre 2023" ~ "mediumpurple1",
      trimestre == "2º trimestre 2022" ~ "coral2",
      TRUE ~ "gray70"
    )
  ) |>
    ggplot2::ggplot(aes(x = trimestre, y = peso_medio_carcaca, fill = cor)) +
                geom_col() +
                geom_hline(yintercept = 267., lty = 3, color = "gray30") +
                theme_swd_line  +
                scale_y_continuous(labels = scales::comma) +
                labs(title =
                "Abate de bovinos no Brasil (Peso medio da carcaça - kg)",
                    subtitle = "# Relatório trimestral de abate
                    by Ítalo Monteiro
                    Source: IBGE [open data(2023)]",
                    x = "Trimestre"
                    ) +
                scale_x_discrete(
                    limits = c(
                    "1º trimestre 2021",
                    "2º trimestre 2021",
                    "3º trimestre 2021",
                    "4º trimestre 2021",
                    "1º trimestre 2022",
                    "2º trimestre 2022",
                    "3º trimestre 2022",
                    "4º trimestre 2022",
                    "1º trimestre 2023",
                    "2º trimestre 2023")
                ) +
                guides(fill = FALSE) +
                annotate(
                  "text", label = "Média do período",
                  x = 1.5, y = 269., size = 4, colour = "gray45"
                ) +
                geom_text(
                    data = abate[abate$ano == 2023 &
                        abate$trimestre == "2º trimestre 2023" &
                            abate$tipo_de_rebanho == "Bovinos",],
                            aes(label = scaleFUN(peso_medio_carcaca)),
                            hjust = 0.5,
                            vjust = -0.5,
                            size = 5,
                            color = "#346116",
                            fontface = "bold") +
                geom_text(
                    data = abate[abate$ano == 2023 &
                        abate$trimestre == "1º trimestre 2023" &
                            abate$tipo_de_rebanho == "Bovinos",],
                            aes(label = scaleFUN(peso_medio_carcaca)),
                            hjust = 0.5,
                            vjust = -0.8,
                            size = 4,
                            color = "gray50",
                            fontface = "bold") +
                geom_text(
                    data = abate[abate$ano == 2022 &
                        abate$trimestre == "2º trimestre 2022" &
                            abate$tipo_de_rebanho == "Bovinos",],
                            aes(label = scaleFUN(peso_medio_carcaca)),
                            hjust = 0.5,
                            vjust = -0.5,
                            size = 4,
                            color = "gray50",
                            fontface = "bold")
peso_medio_carcaca_2tri_2023
```

```{r}
ggsave("Images/peso_medio_carcaca_2tri_2023.png",
    plot = peso_medio_carcaca_2tri_2023,
    dpi = 1200,
    width = ,
    height = )
```