---
title: "Abate bovino no  3º trimestre 2023 "
description: "Quantitativo por categoria atualizado em  09 de novembro de 2023 pelo IBGE"
author: 
    - name: "Ítalo Marques-Monteiro"
    - email: "italo.marques.monteiro@outlook.com"
    - github: https://github.com/italomarquesmonteiro
    - kaggle: https://www.kaggle.com/talomarquesmonteiro
    - linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    - lattes: http://lattes.cnpq.br/7174985368517137
    - orcid_id: https://orcid.org/0000-0003-4367-1034
    - affiliation: Smart Data  
        
date: "2023-09-11"
output: html_document
---

Informações:
[IBGE](https://www.ibge.gov.br/)
[Comunidado](https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/38302-abate-de-bovinos-frangos-e-suinos-cresce-no-3-trimestre-de-2023)
[Dados](https://sidra.ibge.gov.br/tabela/6829)

```{r}
library(tidyverse)
```

```{r}
abate_br  <- sidrar::get_sidra(
    api = "/t/6829/n1/all/v/all/p/all/c12716/115236/c79/all") |>
    janitor::clean_names("snake") |>
    dplyr::glimpse()

abate <- abate_br |>
    dplyr::select(
        valor,
            tipo_de_rebanho,
                data_trimestre = trimestre_codigo,
                trimestre,
                    variavel
    ) |>
    dplyr::mutate(
        data_trimestre = lubridate::yq(data_trimestre),
        ano = lubridate::year(data_trimestre)
    ) |>
    tidyr::pivot_wider(names_from = variavel, values_from = valor) |>
    dplyr::rename(
        cabeca = `Animais abatidos`, carcaca = `Peso total das carcaças`) |>
    dplyr::mutate(peso_car = carcaca / cabeca) |>
    dplyr::glimpse()
```

```{r}
abate |>
    dplyr::filter(tipo_de_rebanho == "Bovinos") |>
    dplyr::arrange(desc(peso_car))
```



  Tabela     trimestre         cabeças      valor-site        link-fonte
  1092   4º trimestre 2013    8.888.188    8,9 milhões     ("https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/14584-asi-abates-de-bovinos-suinos-e-frangos-aquisicao-de-leite-e-producao-de-ovos-sao-recordes-em-2013")
  1092   3º trimestre 2013    8.859.325    8,913 milhões   ("https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/14532-asi-abates-de-bovinos-suinos-e-frangos-no-3-trimestre-foram-recordes")   
  6829   3º trimestre 2023    8.850.720    8,85 milhões    ("https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/38302-abate-de-bovinos-frangos-e-suinos-cresce-no-3-trimestre-de-2023")   

```{r}
colors <- c("#929d37", "#064a81")
title_text <- glue::glue('Quantitativo de <span style = "color:{colors[2]}">**cabeças bovina**</span><br>guiadas para abate no 3º trimestre de 2023') # nolint
subtitle_text <- glue::glue("")
caption_text <- glue::glue('**Dados preliminares:** IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2023)] | **Plot:** Ítalo Monteiro') # nolint
grafico_abt <- abate |>
    dplyr::filter(
        tipo_de_rebanho == "Bovinos" &
            trimestre >= "1º trimestre 2021"
    ) |>
    #dplyr::summarise(media = mean(valor), mediana = median(valor)) |>
    ggplot2::ggplot(
        aes(
            x = trimestre,
                y = cabeca
        )
    ) +
    ggchicklet::geom_chicklet(
        aes(
            fill = ifelse(
                trimestre %in% c(
                    "3º trimestre 2022",
                        "2º trimestre 2023",
                            "3º trimestre 2023"),
                                "high", "default"
            )
        ),
        radius = grid :: unit(3, "mm")) +
    scale_fill_manual(
        values = c(
            high = "#064a81",
                default = "grey70"
        )
    ) +
     geom_hline(
        yintercept = 7541099,
            lty = 3,
                color = "gray30"
    ) +
    scale_y_continuous(
        labels = scales::comma
    ) +
    labs(
        title = title_text,
            subtitle = subtitle_text,
                caption = caption_text
    ) +
    theme(
        plot.title = ggtext::element_markdown(face = "bold", family = "Source Sans Pro", size = 48, hjust = 0, color = "gray40",), # nolint
        plot.subtitle = ggtext::element_markdown(face = "bold", family = "Fira Sans Pro", size = 15, color = "gray50", hjust = 0.1), # nolint
        plot.caption = ggtext::element_markdown(face = "italic", family = "Fira Sans Pro", size = 12, color = "gray50"), # nolint
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        #plot.margin = margin(rep(15, 4)),
        panel.background = element_rect(fill = "white", color = "white"),
        plot.background = element_rect(fill = "white"),
        line = element_blank()#,
        #rect = element_blank()
        ) +
    annotate("text", label = "8,85 milhões", x = 11, y = 8990000, size = 5, family = "Fira Sans Pro", colour = "#064a81") +
    annotate("text", label = "8,36", x = 10, y = 8350000, size = 4, colour = "gray45") +
    annotate("text", label = "7,96", x = 7, y = 7960000, size = 4, colour = "gray45") +
    scale_x_discrete(
        limits = c(
            "1º trimestre 2021",
                "2º trimestre 2021",
                    "3º trimestre 2021",
                        "4º trimestre 2021",
                            "1º trimestre 2022",
                                "2º trimestre 2022",
                            "3º trimestre 2022",
                        "4º trimestre 2022",
                    "1º trimestre 2023",
                "2º trimestre 2023",
            "3º trimestre 2023"
            )
        ) +
    guides(
        fill = FALSE
    ) +
    annotate( # média:7541099 ; mediana:7382158
        "text",
            label = "Média do período",
                x = 1,
                    y = 7650000,
                        size = 4,
                            colour = "gray45"
    )
grafico_abt
```

```{r}
ggsave(
    "Images/abate_preliminar_3tri23.png",
        plot = grafico_abt,
            dpi = 500,
                width = 13.8,
                 height = 9
    )
```




```{r}
colors <- c("#929d37", "#064a81")
title_text <- glue::glue('O maior volume de <span style = "color:{colors[1]}">**toneladas de carcaça**</span><br> bovina produzidas na história')
subtitle_text <- glue::glue("")
caption_text <- glue::glue('**Dados preliminares:** IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2023)] | **Plot:** Ítalo Monteiro')

grafico_carcaca <- abate |>
    dplyr::filter(
        tipo_de_rebanho == "Bovinos" &
            trimestre >= "1º trimestre 2021"
    ) |>
    #dplyr::summarise(media = mean(peso_car), mediana = median(peso_car)) |>
    ggplot2::ggplot(
        aes(
            x = trimestre,
                y = carcaca
        )
    ) +
    ggchicklet::geom_chicklet(
        aes(
            fill = ifelse(
                trimestre %in% c(
                    "3º trimestre 2022",
                        "2º trimestre 2023",
                            "3º trimestre 2023"),
                                "high", "default"
            )
        ),
        radius = grid :: unit(3, "mm")) +
    scale_fill_manual(
        values = c(
            high = "#929d37",
                default = "grey70"
        )
    ) +
     geom_hline(
        yintercept = 1986839568,
            lty = 3,
                color = "gray30"
    ) +
    scale_y_continuous(
        labels = scales::comma
    ) +
    labs(
        title = title_text,
            subtitle = subtitle_text,
                caption = caption_text
    ) +
    theme(
        plot.title = ggtext::element_markdown(face = "bold", family = "Source Sans Pro", size = 48, hjust = 0, color = "gray40",), # nolint
        plot.subtitle = ggtext::element_markdown(face = "bold", family = "Fira Sans Pro", size = 15, color = "gray50", hjust = 0.1), # nolint
        plot.caption = ggtext::element_markdown(face = "italic", family = "Fira Sans Pro", size = 12, color = "gray50"), # nolint
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        #plot.margin = margin(rep(15, 4)),
        panel.background = element_rect(fill = "white", color = "white"),
        plot.background = element_rect(fill = "white"),
        line = element_blank()#,
        #rect = element_blank()
        ) +
    annotate("text", label = "2,36 milhões", x = 11, y = 2388203437, size = 5, family = "Fira Sans Pro", colour = "#929d37") +
    annotate("text", label = "2,17", x = 10, y = 2173810104, size = 4, colour = "gray45") +
    annotate("text", label = "2,16", x = 7, y = 2153264313, size = 4, colour = "gray45") +
    scale_x_discrete(
        limits = c(
            "1º trimestre 2021",
                "2º trimestre 2021",
                    "3º trimestre 2021",
                        "4º trimestre 2021",
                            "1º trimestre 2022",
                                "2º trimestre 2022",
                            "3º trimestre 2022",
                        "4º trimestre 2022",
                    "1º trimestre 2023",
                "2º trimestre 2023",
            "3º trimestre 2023"
            )
        ) +
    guides(
        fill = FALSE
    ) +
    annotate( # média:1 986 839 568 ; mediana:1 984 748 758
        "text",
            label = "Média do período",
                x = 1,
                    y = 2020000000,
                        size = 4,
                            colour = "gray45"
    )
grafico_carcaca
```

```{r}
ggsave(
    "Images/carcaca_preliminar_3tri23.png",
        plot = grafico_carcaca,
            dpi = 500,
                width = 13.8,
                    height = 9
    )
```

```{r}
colors <- c("#929d37", "#064a81", "mediumpurple1")
title_text <- glue::glue('<span style = "color:{colors[3]}">**Peso da carcaça bovina**</span><br>entre os trimestre de 2021 a 2023')
subtitle_text <- glue::glue("")
caption_text <- glue::glue('**Dados preliminares:** IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2023)] | **Plot:** Ítalo Monteiro')
grafico_peso_car <- abate |>
    dplyr::filter(
        tipo_de_rebanho == "Bovinos" &
            trimestre >= "1º trimestre 2021"
    ) |>
    #dplyr::summarise(media = mean(peso_car), mediana = median(peso_car)) |>
    ggplot2::ggplot(
        aes(
            x = trimestre,
                y = peso_car
        )
    ) +
    ggchicklet::geom_chicklet(
        aes(
            fill = ifelse(
                trimestre %in% c(
                    "3º trimestre 2022",
                        "2º trimestre 2023",
                            "3º trimestre 2023"),
                                "high", "default"
            )
        ),
        radius = grid :: unit(3, "mm")) +
    scale_fill_manual(
        values = c(
            high = "mediumpurple1",
                default = "grey70"
        )
    ) +
     geom_hline(
        yintercept = 264,
            lty = 3,
                color = "gray30"
    ) +
    scale_y_continuous(
        labels = scales::comma
    ) +
    labs(
        title = title_text,
            subtitle = subtitle_text,
                caption = caption_text
    ) +
    theme(
        plot.title = ggtext::element_markdown(face = "bold", family = "Source Sans Pro", size = 48, hjust = 0, color = "gray40",), # nolint
        plot.subtitle = ggtext::element_markdown(face = "bold", family = "Fira Sans Pro", size = 15, color = "gray50", hjust = 0.1), # nolint
        plot.caption = ggtext::element_markdown(face = "italic", family = "Fira Sans Pro", size = 12, color = "gray50"), # nolint
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        #plot.margin = margin(rep(15, 4)),
        panel.background = element_rect(fill = "white", color = "white"),
        plot.background = element_rect(fill = "white"),
        line = element_blank()#,
        #rect = element_blank()
        ) +
    annotate("text", label = "266 kg/cab", x = 11, y = 270, size = 5, family = "Fira Sans Pro", colour = "mediumpurple1") +
    annotate("text", label = "260", x = 10, y = 268, size = 4, colour = "gray45") +
    annotate("text", label = "272", x = 7, y = 275, size = 4, colour = "gray45") +
    scale_x_discrete(
        limits = c(
            "1º trimestre 2021",
                "2º trimestre 2021",
                    "3º trimestre 2021",
                        "4º trimestre 2021",
                            "1º trimestre 2022",
                                "2º trimestre 2022",
                            "3º trimestre 2022",
                        "4º trimestre 2022",
                    "1º trimestre 2023",
                "2º trimestre 2023",
            "3º trimestre 2023"
            )
        ) +
    guides(
        fill = FALSE
    ) +
    annotate( # média:7541099 ; mediana:7382158
        "text",
            label = "Média do período",
                x = 1,
                    y = 270,
                        size = 4,
                            colour = "gray45"
    )
grafico_peso_car
```

```{r}
ggsave(
    "Images/abate_peso_car.png",
        plot = grafico_peso_car,
            dpi = 500,
                width = 13.8,
                    height = 9
    )
```
