---
title: "Cabeças Abatidas"
description: "Número de animais guiados para abate sob algum serviço de inspeção"
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Smart Data  
        
date: "2024-09-05"
output: html_document
---
 Bibliiotecas
```{r}
library(tidyverse)
```

 Adicionar fontes
```{r}
# Adicionar fontes
font <- "Josefin Sans"
font2 <- "Open Sans"
font3 <- "Permanent Marker"
sysfonts::font_add_google(family = font, font, db_cache = FALSE)
sysfonts::font_add_google(family = font2, font2, db_cache = FALSE)
sysfonts::font_add_google(family = font3, font3, db_cache = FALSE)
sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf")
showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)
```


 Base original: Abate por categoria, BR
```{r}
base_original <- sidrar::get_sidra(
    api = "/t/1092/n1/all/v/284,285/p/all/c12716/115236/c18/55,56,111734,111735/c12529/118225") |>
    janitor::clean_names("snake") |>
    dplyr::glimpse()
```


 Base manipulada
```{r}
abt <- base_original |>
    dplyr::select(
        valor,
        categoria = tipo_de_rebanho_bovino,
        data_trimestre = trimestre_codigo,
        trimestre,
        variavel
    ) |>
    dplyr::mutate(
        data_trimestre = lubridate::yq(data_trimestre),
        ano = lubridate::year(data_trimestre)
    ) |>
    tidyr::pivot_wider(
        names_from = variavel,
        values_from = valor
    ) |>
    dplyr::rename(
        cabeca = `Animais abatidos`,
        carcaca = `Peso total das carcaças`
    ) |>
    dplyr::mutate(
        peso_car = carcaca / cabeca
    ) |>
    dplyr::glimpse()
```


Participação de Vacas e novilhas no abate total
```{r}
# Criando a nova coluna para identificar machos e fêmeas
abt <- abt |>
  mutate(
    sexo = case_when(
      categoria %in% c("Bois", "Novilhos") ~ "Macho",
      categoria %in% c("Vacas", "Novilhas") ~ "Fêmea"
    ), .before = data_trimestre
  )
# abate total
abt  |>
    group_by(trimestre) |>
    summarise(total = sum(cabeca)) |>
    arrange(desc(total))

abt1 <- abt |>
  #dplyr::filter(ano >= 2010) |>
  group_by(ano, trimestre, categoria, sexo) |>
  summarise(
    total_cabeca = sum(cabeca)
    #,.groups = 'drop'
  ) |>
  group_by(ano, trimestre) |>
  mutate(
    total_geral = sum(total_cabeca),
    percentual = (total_cabeca / total_geral) * 100,
    trimestre = str_replace_all(trimestre, c(
        "1º trimestre 19" = "1T ",
        "2º trimestre 19" = "2T ",
        "3º trimestre 19" = "3T ",
        "4º trimestre 19" = "4T ",
        "1º trimestre 20" = "1T ",
        "2º trimestre 20" = "2T ",
        "3º trimestre 20" = "3T ",
        "4º trimestre 20" = "4T "))
    )

# Adicionar captions

github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"

bg <- "white"
txt_col <- "grey70"
colors <- "gray40"
title_text <- glue::glue("Percentual de Abate de Fêmeas:")
subtitle_text <- glue::glue("Participação trimestral de vacas e novilhas sobre o total abatido")
caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>",
  #"**Nota:** Média do período: 37.9%<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey70'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: skyblue;'>{linkedin_icon};</span> 
  <span style='color: grey70'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey70'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: grey70'>{instagram_username}</span>"
)

# Definindo as cores base
cores_base <- c("#003f5c", "#2f4b7c", "#665191", "#a05195", "#d45087", "#f95d6a", "#ff7c43", "#ffa600")
# Gerando uma paleta com 28 cores
pal <- colorRampPalette(cores_base)(110)

plot_facet_femea <- abt1 |>
  filter(sexo == "Fêmea") |> 
  ggplot(aes(x = trimestre, y = percentual, fill = "skyblue")) +  # Usando 'categoria' como preenchimento
  ggchicklet::geom_chicklet(fill = "grey70", color = "grey50", alpha = 0.7) +
  guides(fill = "none") +
  facet_wrap(~categoria) +
  scale_y_continuous(breaks = seq(0, 45, 10), labels = scales::dollar_format(
    prefix = "", suffix = "%")) +
    scale_x_discrete(
    limits = c(
        "1T 97", "2T 97", "3T 97", "4T 97",
        "1T 98", "2T 98", "3T 98", "4T 98",
        "1T 99", "2T 99", "3T 99", "4T 99",
        "1T 00", "2T 00", "3T 00", "4T 00",
        "1T 01", "2T 01", "3T 01", "4T 01",
        "1T 02", "2T 02", "3T 02", "4T 02",
        "1T 03", "2T 03", "3T 03", "4T 03",
        "1T 04", "2T 04", "3T 04", "4T 04",
        "1T 05", "2T 05", "3T 05", "4T 05",
        "1T 06", "2T 06", "3T 06", "4T 06",
        "1T 07", "2T 07", "3T 07", "4T 07",
        "1T 08", "2T 08", "3T 08", "4T 08",
        "1T 09", "2T 09", "3T 09", "4T 09",
        "1T 10", "2T 10", "3T 10", "4T 10",
        "1T 11", "2T 11", "3T 11", "4T 11",
        "1T 12", "2T 12", "3T 12", "4T 12",
        "1T 13", "2T 13", "3T 13", "4T 13",
        "1T 14", "2T 14", "3T 14", "4T 14",
        "1T 15", "2T 15", "3T 15", "4T 15",
        "1T 16", "2T 16", "3T 16", "4T 16",
        "1T 17", "2T 17", "3T 17", "4T 17",
        "1T 18", "2T 18", "3T 18", "4T 18",
        "1T 19", "2T 19", "3T 19", "4T 19",
        "1T 20", "2T 20", "3T 20", "4T 20",
        "1T 21", "2T 21", "3T 21", "4T 21",
        "1T 22", "2T 22", "3T 22", "4T 22",
        "1T 23", "2T 23", "3T 23", "4T 23",
        "1T 24", "2T 24"
        )
    ) +
    labs(
    title = title_text,
    subtitle = subtitle_text,
    caption = caption_text
  ) +
  theme(
    plot.title = ggtext::element_markdown(face = "bold", family = font3, size = 40, color = "gray80", hjust = 0.5),
    plot.subtitle = element_text(face = "italic", family = font2, size = 18, color = "gray70", hjust = 0.5),
    plot.caption = ggtext::element_markdown(face = "bold", family = font, size = 9, color = txt_col, hjust = 0, margin = margin(10, 20, 20, 20),  lineheight = 1.2),
    panel.background = element_rect(fill = "grey25", color = "grey25"),
    panel.grid = element_line(color = "grey25"),
    panel.grid.major.y = element_line(color = "grey40", size = 0.5, linetype = 1),
    panel.grid.minor.y = element_line(color = "grey35", size = 0.5, linetype = 3),
    plot.background = element_rect(fill = "grey25"),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = ggtext::element_markdown(face = "bold", family = font2, size = 10, color = "gray40"),
    axis.text.x = ggtext::element_markdown(face = "bold", family = font2, size = 4, color = "gray40", angle = 90, hjust = 1, vjust = 0.5),
    axis.ticks.length.x = unit(-0.8, "cm"),
    axis.ticks.x = element_line(color = "grey40", size = 0.3),
    strip.text = ggtext::element_markdown(color = "grey20", size = 14, face = "bold", family = font)
  )

ggsave(
    ".github\\.vscode\\Trimestrais\\Percentual de participação trimestral - Vacas e Novilhas.png",
    plot = plot_facet_femea,
    width = 17.1,
    height = 10.2,
    dpi = 300)
```


 Participação anual de fêmeas no abate total 
```{r}
# Criando a nova coluna para identificar machos e fêmeas
abt <- abt |>
  mutate(
    sexo = case_when(
      categoria %in% c("Bois", "Novilhos") ~ "Macho",
      categoria %in% c("Vacas", "Novilhas") ~ "Fêmea"
    )
  )

# Calculando o total de cabeças por sexo e o percentual
percentual_abate_anual <- abt |>
  #dplyr::filter(ano >= 2010) |>
  group_by(ano, sexo) |>
  summarise(
    total_cabeca = sum(cabeca),
    .groups = 'drop'
  ) |>
  group_by(ano) |>
  mutate(
    total_geral = sum(total_cabeca),
    percentual = (total_cabeca / total_geral) * 100
  )  |> tail()

# Adicionar fontes
font <- "Josefin Sans"
font2 <- "Open Sans"
font3 <- "Permanent Marker"
sysfonts::font_add_google(family = font, font, db_cache = FALSE)
sysfonts::font_add_google(family = font2, font2, db_cache = FALSE)
sysfonts::font_add_google(family = font3, font3, db_cache = FALSE)
sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf")
showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)

github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"

bg <- "white"
txt_col <- "grey70"
colors <- "gray40"
title_text <- glue::glue("Percentual de Abate de Fêmeas:")
subtitle_text <- glue::glue("Participação anual de fêmeas sobre o total abatido até o 2º trimestre de 2024")
caption_text <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>",
  "**Nota:** Média do período: 37.9%<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey70'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: skyblue;'>{linkedin_icon};</span> 
  <span style='color: grey70'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey70'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: grey70'>{instagram_username}</span>"
)

# Definindo as cores base
cores_base <- c("#003f5c", "#2f4b7c", "#665191", "#a05195", "#d45087", "#f95d6a", "#ff7c43", "#ffa600")

# Gerando uma paleta com 28 cores
pal <- colorRampPalette(cores_base)(28)

# Calculando o percentual médio de abate
percentual_medio_periodo <- percentual_abate_anual |>
  filter(sexo == "Fêmea") |>  # Filtrar apenas os dados de fêmeas
  ungroup() |>  # Remover agrupamento por ano
  summarise(
    percentual_medio = mean(percentual, na.rm = TRUE)  # Calcular a média dos percentuais
  ) |>
  mutate(percentual_medio = round(percentual_medio, digits = 1)) |> 
  pull(percentual_medio)  # Extrair o valor numérico

# Criando o gráfico com percentual de fêmeas abatidas
part_abt_femeas <- percentual_abate_anual |>
  dplyr::filter(sexo == "Fêmea") |>  # Filtrar apenas os dados de fêmeas
  ggplot(aes(x = as.factor(ano), y = percentual, fill = as.factor(ano))) +  # Criar o gráfico de barras
  ggchicklet::geom_chicklet(position = "dodge", width = 0.7, color = "grey40", size = 1.5) +  # Barras arredondadas
  geom_hline(yintercept = percentual_medio_periodo, linetype = 3, color = "grey50") +
  geom_text(
  aes(label = sprintf("%.1f%%", percentual)),
  position = position_dodge(width = 0.7),
  vjust = -0.5,
  size = 3.5,
  fontface = "bold",
  family = font,
  color = "grey80"
) +  # Adicionar labels com uma casa decimal
  scale_fill_manual(values = pal) +  # Aplicar a paleta de cores
  labs(
    title = title_text,
    subtitle = subtitle_text,
    caption = caption_text
  ) +
  theme(
    plot.title = ggtext::element_markdown(face = "bold", family = font3, size = 40, color = "gray80", hjust = 0.1),
    plot.subtitle = element_text(face = "italic", family = font2, size = 18, color = "gray70", hjust = 0.1),
    plot.caption = ggtext::element_markdown(face = "bold", family = font, size = 9, color = txt_col, hjust = 0, margin = margin(10, 20, 20, 20),  lineheight = 1.2),
    panel.background = element_rect(fill = "grey25", color = "grey25"),
    panel.grid = element_line(color = "grey25"),
    panel.grid.major.y = element_line(color = "grey25", size = 0.5, linetype = 1),
    panel.grid.minor.y = element_line(color = "grey25", size = 0.5, linetype = 1),
    plot.background = element_rect(fill = "grey25"),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = ggtext::element_markdown(face = "bold", family = font2, size = 13, color = "gray40", angle = 90, hjust = 1, vjust = 0.5),
    axis.ticks.length.x = unit(-0.8, "cm"),
    axis.ticks.x = element_line(color = "grey40", size = 1)
    )

ggsave(
    ".github\\.vscode\\Trimestrais\\Percentual de participação anual do abate de fêmeas.png",
    plot = part_abt_femeas,
    #width = ,
    #height = ,
    dpi = 300
    )
```


Participação de fêmeas no abate Trimestral
```{r}
# Criando a nova coluna para identificar machos e fêmeas
abt <- abt |>
  mutate(
    sexo = case_when(
      categoria %in% c("Bois", "Novilhos") ~ "Macho",
      categoria %in% c("Vacas", "Novilhas") ~ "Fêmea"
    )
  )

# Calculando o total de cabeças por sexo e o percentual
percentual_abate_trimestral <- abt |>
  #dplyr::filter(ano >= 2010) |>
  group_by(ano, trimestre, sexo) |>
  summarise(
    total_cabeca = sum(cabeca),
    .groups = 'drop'
  ) |>
  group_by(ano, trimestre) |>
  mutate(
    total_geral = sum(total_cabeca),
    percentual = (total_cabeca / total_geral) * 100
  ) #|> dplyr::filter(sexo == "Fêmea") |> tail()

# Groups:   ano, trimestre [6]
#    ano trimestre         sexo  total_cabeca total_geral percentual
#  <dbl> <chr>             <chr>        <dbl>       <dbl>      <dbl>
#1  2023 1º trimestre 2023 Fêmea      3352142     7466521       44.9
#2  2023 2º trimestre 2023 Fêmea      3731168     8478163       44.0
#3  2023 3º trimestre 2023 Fêmea      3529741     8997920       39.2
#4  2023 4º trimestre 2023 Fêmea      3588870     9159202       39.2
#5  2024 1º trimestre 2024 Fêmea      4335154     9337938       46.4
#6  2024 2º trimestre 2024 Fêmea      4508165     9959699       45.3

# Adicionar fontes
font <- "Josefin Sans"
font2 <- "Open Sans"
font3 <- "Permanent Marker"
sysfonts::font_add_google(family = font, font, db_cache = FALSE)
sysfonts::font_add_google(family = font2, font2, db_cache = FALSE)
sysfonts::font_add_google(family = font3, font3, db_cache = FALSE)
sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf")
showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)

github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"

bg <- "white"
txt_col <- "grey70"
colors <- "gray40"
title_text1 <- glue::glue("Percentual de Abate de Fêmeas:")
subtitle_text1 <- glue::glue("Comportamento agrupado por trimestre da participação de fêmeas sobre o total abatido")
caption_text1 <- glue::glue(
  "**Dados:**  IBGE [Diretoria de Pesquisas Agropecuárias, Coordenação de Agropecuária, Pesquisa Trimestral do Abate de Animais(2024)]<br>",
  "**Nota:** Média do período: 37.9%<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: white;'>{github_icon};</span> 
  <span style='color: grey70'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: skyblue;'>{linkedin_icon};</span> 
  <span style='color: grey70'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: grey70'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: grey70'>{instagram_username}</span>"
)

# Definindo as cores base
cores_base <- c("#003f5c", "#2f4b7c", "#665191", "#a05195", "#d45087", "#f95d6a", "#ff7c43", "#ffa600")

# Gerando uma paleta com 28 cores
pal <- colorRampPalette(cores_base)(110)

# Calculando o percentual médio de abate
percentual_medio_periodo_tri <- percentual_abate_trimestral |>
  filter(sexo == "Fêmea") |>  # Filtrar apenas os dados de fêmeas
  ungroup() |>  # Remover agrupamento por ano
  summarise(
    percentual_medio = mean(percentual, na.rm = TRUE)  # Calcular a média dos percentuais
  ) |>
  mutate(percentual_medio = round(percentual_medio, digits = 1)) |> 
  pull(percentual_medio)  # Extrair o valor numérico

# Criando o gráfico com percentual de fêmeas abatidas
part_abt_femeas_tri <- percentual_abate_trimestral |>
  dplyr::filter(sexo == "Fêmea") |>  # Filtrar apenas os dados de fêmeas
  ggplot(aes(x = as.factor(trimestre), y = percentual, fill = as.factor(trimestre))) +  # Criar o gráfico de barras
  ggchicklet::geom_chicklet(position = "dodge", width = 0.7, color = "grey40") +  # Barras arredondadas
  geom_hline(yintercept = percentual_medio_periodo_tri, linetype = 3, color = "grey50") +
  #geom_text(
  #aes(label = sprintf("%.1f%%", percentual)),
  #position = position_dodge(width = 0.7),
  #vjust = -0.5,
  #size = 3.5,
  #fontface = "bold",
  #family = font,
  #color = "grey80"
  #) +  # Adicionar labels com uma casa decimal
  scale_fill_manual(values = pal) +  # Aplicar a paleta de cores
  labs(
    title = title_text1,
    subtitle = subtitle_text1,
    caption = caption_text1
  ) +
  theme(
    plot.title = ggtext::element_markdown(face = "bold", family = font3, size = 40, color = "gray80", hjust = 0.1),
    plot.subtitle = element_text(face = "italic", family = font2, size = 18, color = "gray70", hjust = 0.1),
    plot.caption = ggtext::element_markdown(face = "bold", family = font, size = 9, color = txt_col, hjust = 0, margin = margin(10, 20, 20, 20),  lineheight = 1.2),
    panel.background = element_rect(fill = "grey25", color = "grey25"),
    panel.grid = element_line(color = "grey25"),
    panel.grid.major.y = element_line(color = "grey25", size = 0.5, linetype = 1),
    panel.grid.minor.y = element_line(color = "grey25", size = 0.5, linetype = 1),
    plot.background = element_rect(fill = "grey25"),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = ggtext::element_markdown(face = "bold", family = font2, size = 8, color = "gray40", angle = 90, hjust = 1, vjust = 0.5),
    axis.ticks.length.x = unit(-0.8, "cm"),
    axis.ticks.x = element_line(color = "grey40", size = 1)
    ) +
  geom_vline(xintercept = 28.5, color = "grey70", linetype = 1) +
  geom_vline(xintercept = 56.5, color = "grey70", linetype = 1)+
  geom_vline(xintercept = 83.5, color = "grey70", linetype = 1)

ggsave(
    ".github\\.vscode\\Trimestrais\\Percentual de participação trimestral do abate de fêmeas.png",
    plot = part_abt_femeas_tri,
    #width = 20,
    #height = 9.9 ,
    dpi = 300
    )
```


```{r}
# Criar uma nova coluna trimestre_ano combinando o trimestre e o ano
percentual_abate_trimestral <- percentual_abate_trimestral |>
  mutate(trimestre_ano = paste(trimestre, ano))  # Combina trimestre e ano

# Definir os níveis da nova coluna com base na ordem cronológica correta
percentual_abate_trimestral <- percentual_abate_trimestral |>
  mutate(trimestre_ano = factor(trimestre_ano, 
                                levels = unique(paste(trimestre, ano))))

# Agora, gerar o gráfico usando essa nova coluna `trimestre_ano` como eixo x
part_abt_femeas_tri1 <- percentual_abate_trimestral |>
  dplyr::filter(sexo == "Fêmea") |>  # Filtrar apenas os dados de fêmeas
  ggplot(aes(x = trimestre_ano, y = percentual, fill = as.factor(trimestre_ano))) +  # Usar a nova coluna como eixo x
  ggchicklet::geom_chicklet(color = "grey40") +  # Barras arredondadas
  geom_hline(yintercept = percentual_medio_periodo_tri, linetype = 3, color = "grey50") +
  scale_fill_manual(values = pal) +  # Aplicar a paleta de cores
  labs(
    title = title_text1,
    subtitle = subtitle_text1,
    caption = caption_text1
  ) +
  theme(
    plot.title = ggtext::element_markdown(face = "bold", family = font3, size = 40, color = "gray80", hjust = 0.1),
    plot.subtitle = element_text(face = "italic", family = font2, size = 18, color = "gray70", hjust = 0.1),
    plot.caption = ggtext::element_markdown(face = "bold", family = font, size = 9, color = txt_col, hjust = 0, margin = margin(10, 20, 20, 20),  lineheight = 1.2),
    panel.background = element_rect(fill = "grey25", color = "grey25"),
    panel.grid = element_line(color = "grey25"),
    panel.grid.major.y = element_line(color = "grey25", size = 0.5, linetype = 1),
    panel.grid.minor.y = element_line(color = "grey25", size = 0.5, linetype = 1),
    plot.background = element_rect(fill = "grey25"),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = ggtext::element_markdown(face = "bold", family = font2, size = 8, color = "gray40", angle = 90, hjust = 1, vjust = 0.5),
    axis.ticks.length.x = unit(-0.8, "cm"),
    axis.ticks.x = element_line(color = "grey40", size = 1)
  )

ggsave(
    ".github\\.vscode\\Trimestrais\\Percentual de participação trimestral do abate de fêmeas1.png",
    plot = part_abt_femeas_tri1,
    #width = 20,
    #height = 9.9 ,
    dpi = 300
    )
```